### ISSUE TITLE
Cluster by breakpoints + exons

### ISSUE THREAD

**Issue by pintoa1-mskcc** [ccmbioinfo/MetaFusion-Clinical#1]
Clinical Metafusion now clusters by breakpoint and exon instead of breakpoint and gene name. Why was there a change to include exon instead of only using the bedtools pairtoPair on the breakpoints?

**Comment by mapostolides** [comment]
Hello! As the author of the code, what I remember implementing is a clustering by breakpoints alone using bedtools pairToPair with a slop of 10. Is there a case of merge you have seen that differs from this implementation?

**Comment by pintoa1-mskcc** [comment]
https://github.com/ccmbioinfo/MetaFusion-Clinical/blob/f29363c812f59e436aa4f5a62d0292b31d263b6b/scripts/intersect_breakpoints.per_sample.py#L51-L104 

Apologies! I was looking at the line in the script above and didnt notice that there was an `exit(0)` to skip the rest of the code. Im assuming that the code will skip the rest of the script once it hits the exit?

**Comment by mapostolides** [comment]
Ok good to know! Yes previously I was working on a feature to merge by
exons as well, but we found that for clinical purposes it was better to
merge by breakpoint alone

**Comment by mapostolides** [comment]
And yes the exit(0) will stop the script at that point, if you want to experiment with merging by exon you could comment it and try out the code below that, but we did not use this code for our analysis in the manuscript :)
